### ISSUE TITLE
Loaded check values are not verified, can result in crashes.

### ISSUE THREAD

**Issue by metasansana** [quenktechnologies/dagen#16]
```sh
TypeError: f is not a function
    at Right.chain (../code/development/products/anole/node_modules/@quenk/noni/lib/data/either.js:114:16)
    at chainCheck (../code/development/products/anole/node_modules/@quenk/dagen/lib/compiler/index.js:87:39)
```

**Comment by metasansana** [comment]
Fixed in v1.20.
